apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-eks
  template:
    metadata:
      labels:
        app: flask-eks
    spec:
      containers:
        - name: flask-eks-image
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/webapp:TAG 
          ports:
            - containerPort: 5000